### ISSUE TITLE
Trades API incorrectly processes timestamp_from

### ISSUE THREAD

**Issue by mrosseel** [dan-da/bitsquare_market#1] opened 2016-09-29 18:46 UTC
call: https://market.bitsquare.io/api/trades/?market=btc_eur&limit=2?timestamp_from=1471976042413
result:
[{
    "direction": "BUY",
    "price": "543.32970000",
    "amount": "0.10000000",
    "trade_id": "ad85bb39-d80b-4e7b-8bb4-c9537eaeb5ec",
    "trade_date": 1475150469519
}, {
    "direction": "BUY",
    "price": "542.00640000",
    "amount": "0.10000000",
    "trade_id": "7fa96e8b-eeac-45ee-880e-51e1670bbf2f",
    "trade_date": 1475102281499
}]

While these results are possible:
}, {
    "direction": "SELL",
    "price": "515.65000000",
    "amount": "0.20000000",
    "trade_id": "135e162f-48ef-4722-957b-fa37689b6bbc",
    "trade_date": 1472132093072
}, {
    "direction": "BUY",
    "price": "517.51000000",
    "amount": "0.05000000",
    "trade_id": "76f22a82-be54-486c-9462-1a9c9e4109d8",
    "trade_date": 1471976042413
}]

**Comment by dan-da** [comment] 2016-09-30 21:36
thx for the report.  I'll try and have a look over the weekend.

**Comment by mrosseel** [comment] 2016-10-01 09:26
If you can't fix it don't worry, I have set up a php environment so could fix it myself. But you'll probably fix it quicker :). Let me know if there's progress, thx!

**Comment by Klakurka** [comment] 2016-10-08 03:51
Once this is in place, our team can continue with the API integration.

**Comment by dan-da** [comment] 2016-10-08 21:26
Sorry for the delay. I've been offline.

I notice a few things about this url:
 https://market.bitsquare.io/api/trades/?market=btc_eur&limit=2?timestamp_from=1471976042413
1. It has limit=2 set. So returning only two results is expected behavior.
2. the timestamp_from param is preceded by "?" instead of "&".  This is invalid syntax.
3. The value of timestamp_from is specified in milliseconds rather than seconds as doc'd [here](https://market.bitsquare.io/api/#trades).

In fact, the parameters that the api code actually receive from this url after parsing look like:

```
Array
(
    [market] => btc_eur
    [limit] => 2?timestamp_from=1471976042413
)
```

So the timestamp_from param is ignored entirely and it only due to PHP's "loose" string parsing that the limit=2 is honored.

Please try the following two urls:

 https://market.bitsquare.io/api/trades/?market=btc_eur&limit=2&timestamp_from=1471976042
 https://market.bitsquare.io/api/trades/?market=btc_eur&timestamp_from=1471976042

The returned data looks correct to me, but let me know if you see anything wrong.

**Comment by Klakurka** [comment] 2016-10-09 01:56
Hey Dan,

We believe the sorting is still an issue.

From my initial email:

> If we pass through 1435102281 and a limit of 1, we get back the latest trade (1475102281499 at the time of this writing). We would expect to get back the next trade after the time stamp we provide (something in the 1435XXXXXX range), rather than the most recent trade completed. We do see that it is taking the parameter fine, as a value of 1485102281 returns no results (which makes sense).
> 
> We're thinking that it's because of the order the transactions are listed in (descending instead of ascending).

The key takeaway here is that setting a limit of 2 restricts the dataset to only the most recent 2 trades, regardless of the time stamp entered (as long as it's less than the oldest transaction you get back).

Let me know if you need further clarification.

Example API call: https://market.bitsquare.io/api/trades/?market=btc_eur&limit=2&timestamp_from=12345 (we'd expect the closest transaction to this time stamp to be present in the results, which would also be the oldest assuming no transactions happened before 1970-01-01 @ 3:25am (UTC)).

**Comment by dan-da** [comment] 2016-10-09 06:36
The default sort is descending.  It can be changed to ascending with &sort=asc, eg:

 https://market.bitsquare.io/api/trades/?market=btc_eur&limit=2&timestamp_from=1471976042&sort=asc

I believe that is what you want.

Docs are here
 https://market.bitsquare.io/api/#trades

**Comment by dan-da** [comment] 2016-10-09 06:46
nevermind above comment.  I found an issue.  The ascending sort is being performed after the limit is already applied based on natural (desc) order.   working on a fix.

**Comment by dan-da** [comment] 2016-10-09 07:13
Fixed in git by 3c5c1a57d3a85cbe3e2f16df261f1329177b9a8b.

Not on live server yet.  I'll comment here when it is.

**Comment by dan-da** [comment] 2016-10-10 16:23
The server has been updated.   closing.

**Closed as completed by dan-da** 2016-10-10 16:23 UTC

**Comment by mrosseel** [comment] 2016-10-10 16:33
Thanks dan!

**Comment by ManfredKarrer** [comment] 2016-10-12 20:20
@dan-da Great thanks!

**Comment by Klakurka** [comment] 2016-10-12 21:01
We've tested this and it looks good!

Many thanks.

**Comment by dan-da** [comment] 2016-10-12 23:44
@Klakurka glad to hear it.  thx for the report.
